channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.1.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.2
  - numpy==2.3.5
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.0
name: mlflow-env
